task :default => :jekyll

desc "generate website"
task :jekyll => [ :haml, :sass ] do
  system "jekyll"
end

desc "generate haml"
task :haml do
  system <<-END
    cd _layouts/haml && 
    for f in *.haml; do haml $f ../${f%.haml}.html; done
  END
end

desc "generate sass"
task :sass do
  system <<-END
    cd css/sass && 
    for f in *.sass; do sass $f ../${f%.sass}.css; done
  END
end
